### ISSUE TITLE
Collapse prop not working on collapse/expand feature

### ISSUE THREAD

**Issue by th-gonzalodevarona** [CarlosNZ/json-edit-react#45]
Collapse prop not working properly to collapse/expand object at given level

So, i am aware that if i ctrl/alt + click i will expand all the object but i do not want to do that, i want to put an external button to do the same using a useState variable , i should be able to control that expand/collapse behavior using the `collapse` prop but when i do the following below, the arrow will render as open but won't show the data, is there a way to actually achieve this collapse/expand feature by using an external button and not the ctrl/alt + click ?

<img width="452" alt="Screenshot 2024-03-19 at 3 50 31 PM" src="https://github.com/CarlosNZ/json-edit-react/assets/154278158/a443678d-e3d0-4b20-b100-c4555b1b29a8">

<img width="590" alt="Screenshot 2024-03-19 at 3 50 46 PM" src="https://github.com/CarlosNZ/json-edit-react/assets/154278158/149fada2-c409-4e0d-b30f-037d69368360">

<img width="339" alt="Screenshot 2024-03-19 at 3 49 13 PM" src="https://github.com/CarlosNZ/json-edit-react/assets/154278158/0f5479cf-f11a-4f88-a12a-8577e26aa3bc">

<img width="461" alt="Screenshot 2024-03-19 at 3 52 13 PM" src="https://github.com/CarlosNZ/json-edit-react/assets/154278158/72c38432-388c-45e4-a601-95f0a71de292">

**Comment by CarlosNZ** [comment]
Yes, the object should expand and populate correctly based on the changing `collapse` value as you're doing it. It works as I intended in the [demo](https://carlosnz.github.io/json-edit-react/) -- if you go to the "Star Wars" data set, then change the collapse value to a large number (paste it in rather than using the incrementer), it expands correctly.

So it's strange that its not doing this correctly for your case. I'll try and reproduce your particular setup (with external button) and see if I can see what's going on.

**Comment by CarlosNZ** [comment]
Ah, it looks like you might be using an older version of the package. I can reproduce your issue in v1.7.0, but it's working correctly in 1.8.0 and above.

Please upgrade to the latest (1.8.1) and confirm if that fixes your problem.

**Comment by th-gonzalodevarona** [comment]
The upgrade solved the issue, thank you for your help and quick response! keep the good work up!
