### ISSUE TITLE
Question about the license

### ISSUE THREAD

**Issue by IgorAufricht** [CarlosNZ/json-edit-react#89]
Hi,

I have a question regarding the license this library uses:
* The LICENSE files specifies GPL 3.0 (https://github.com/CarlosNZ/json-edit-react/blob/main/LICENSE)
* The package.json file specified MIT (https://github.com/CarlosNZ/json-edit-react/blob/main/package.json#L13)

Could you please clarify which license is the correct one? (Especially since the licenses are quite different regarding use in commercial products.)

Thank you!

**Comment by rosscarnegie** [comment]
I second this question. 

(For Everyone)
If an application includes a GPL-licensed library, the consuming application needs to also be licensed under the GPL. This means that any application that uses this must make their source code available (even of their modifications) and also permit modifications and redistribution. 

(For the Author)
Obviously you can restrict or unrestrict the library's usage as much or as little as you'd like: that's your perrogative. 

The copy left nature of this license means that it is unlikely to be used in a commercial project. It likely means that some portion of people who are currently using it are likely doing so without realising that it may not be the right choice for them (totally their fault), and that people will be less likely to contribute to the project (which I suspect may be  intentional? I did not see any guidelines for contributions). 

If I can just offer my opinion: the GPL makes sense when you think that the potential users of this library will use it to create software who's primary  functionality is substantially similar to your library i.e. displaying JSON data, and you want people to contribute to the open source project, rather than using it for their own purposes. But if you anticipate this being used as a component of an  application that's potentially, very very different, let's say I want to use this to display data for the next redux and its devtools, then it's probably not the best choice. (because no matter how good my new library was, no one would want to use it commercially because your license essentially means their license trickles down to me and any potential consumer of my library). 

Still, for whatever reason, if you did want to switch the license to something more permissive,  I believe you'd have to consult any other contributors.

**Comment by CarlosNZ** [comment]
Thanks, I haven't really looked into this very seriously, I'm not a lawyer. But I'll have a look in the next week or so and clarify it.

**Comment by CarlosNZ** [comment]
Okay, I've updated the main license file to MIT.

Thanks for pointing this out.

**Comment by IgorAufricht** [comment]
Thank you, much appreciated!
